-
  name: Update README with CLI help
  cmd: |
    { SB_STYLE=md \
      nix run --inputs-from . src-block \
        < README.md
    } 1<> README.md
  required_files:
  - README.md
  - src/main.rs
  sha: 8515ab2f2ccc9b43250dd156440e41e12d2c046d95631182184e0e3b36ba14fd
