-
  name: Update README with CLI help
  cmd: |
    { SB_STYLE=md \
      nix run --inputs-from . src-block \
        < README.md
    } 1<> README.md
  required_files:
  - README.md
  - src/main.rs
  sha: d25ee1f8004577f57d7f2d82b8417cf4d151ee28aa0893506428a493e7f64b49
