[package]
name = "hcz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
thiserror = "1.0.38"
yaml-rust = "0.4.5"
