name: "Build legacy Nix package on Ubuntu"

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15-intel
          - macos-15
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v31
      - name: Building package
        run: |
          system=$(nix-instantiate -E 'builtins.currentSystem' --eval-only | tr -d '"')
          nix-build . -A packages.$system.default
