name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  packages: write
  contents: write

jobs:

  build:
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15-intel
          - macos-15
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v31
      - name: Building package
        run: |
          system=$(nix-instantiate -E 'builtins.currentSystem' --eval-only | tr -d '"')
          nix --extra-experimental-features "nix-command flakes" build .
          mkdir -p ${{ runner.temp }}/bin
          cp -v result/bin/resha ${{ runner.temp }}/bin/resha-static-${system}-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: resha-binary-${{ matrix.runner }}
          path: ${{ runner.temp }}/bin/*
          if-no-files-found: error
          retention-days: 1

  release:
    name: Create Release
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/bin
          pattern: resha-*
          merge-multiple: true

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: ${{ runner.temp }}/bin/resha-*
          # bodyFile: "CHANGELOG.md"      uses: elgohr/Github-Release-Action@v5
