name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  packages: write
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: cachix/install-nix-action@v12

    - name: Build static binary
      run: |
        nix --extra-experimental-features "nix-command flakes" build .
        cp result/bin/resha resha-static-x86_64-unknown-linux-musl

    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        artifacts: "resha-static-x86_64-unknown-linux-musl"
        # bodyFile: "CHANGELOG.md"      uses: elgohr/Github-Release-Action@v5
